on:
  workflow_call:
    inputs:
      solution:
        required: true
        type: string
      publishNuGet:
        default: true
        type: boolean        
      runUnitTests:
        default: true
        type: boolean

defaults:
  run:
    shell: pwsh

jobs:
  build:
    name: nanoFramework
    timeout-minutes: 15
    runs-on: windows-latest
    env:
      BUILD_CONFIGURATION: 'Release'
      GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SOLUTION: ${{ inputs.solution }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup nanoFramework
        uses: nanoframework/nanobuild@v1

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2

      - name: Setup Nerdbank.GitVersioning
        uses: dotnet/nbgv@v0.4.2
        with:
          setAllVars: true

      - name: Install dependencies
        run: nuget restore ${{ env.SOLUTION }}

      - name: Build solution
        run: msbuild ${{ env.SOLUTION }} /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:AssemblyVersion=${{ env.NBGV_AssemblyVersion }} /p:FileVersion=${{ env.NBGV_AssemblyFileVersion }} /p:InformationalVersion=${{ env.NBGV_AssemblyInformationalVersion }}

      - name: Run unit tests
        if: inputs.runUnitTests == true
        uses: CCSWE-nanoFramework/vstest-nanoframework@v1

      - name: Build NuGet packages
        if: inputs.publishNuGet == true
        run: |
          $files = Get-ChildItem -Filter *.nuspec -Recurse | Where-Object Fullname -NotMatch "packages"
          foreach ($file in $files) {
            nuget pack $file.FullName -Version ${{ env.NBGV_NuGetPackageVersion }} -Symbols -SymbolPackageFormat snupkg -properties Configuration=${{ env.BUILD_CONFIGURATION }}
          }

      - name: Publish NuGet packages
        if: inputs.publishNuGet == true && startsWith(github.ref, 'refs/heads/master')
        run: |
          $files = Get-ChildItem -Filter *.nupkg -Recurse | Where-Object Fullname -NotMatch "packages"
          foreach ($file in $files) {
            nuget push $file.FullName -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{ secrets.NUGET_ORG_API_KEY }} -SkipDuplicate
          }
